[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid

[program:php-fpm]
command=php-fpm -F
autorestart=true
priority=10

[program:nginx]
command=nginx -g "daemon off;"
autorestart=true
priority=20

[program:queue]
command=php /var/www/html/artisan queue:work database --sleep=3 --tries=3 --timeout=120
directory=/var/www/html
user=www-data
environment=HOME="/var/www"
autorestart=true
stopwaitsecs=130
priority=30
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
