import { Head, router, useForm } from '@inertiajs/react';
import DashboardLayout from '../../../Layouts/DashboardLayout';
const statuses=['viewed','under_review','shortlisted','interview_scheduled','offered','hired','rejected'];
export default function Index({applications}) {
 const interview=useForm({application_id:applications.data[0]?.id||'',date:'',start_time:'09:00',end_time:'10:00',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,type:'video',meeting_url:'',interviewer:'',notes:''});
 const update=(id,status)=>router.patch(`/employer/candidates/${id}`,{status},{preserveScroll:true});
 const schedule=e=>{e.preventDefault();const id=interview.data.application_id;interview.post(`/applications/${id}/interviews`,{preserveScroll:true});};
 return <DashboardLayout title="Candidates"><Head title="Candidates"/><form onSubmit={schedule} className="glass mb-7 rounded-2xl p-5"><h2 className="font-bold">Schedule interview</h2><div className="mt-4 grid gap-3 md:grid-cols-3 xl:grid-cols-6"><select className="field" value={interview.data.application_id} onChange={e=>interview.setData('application_id',e.target.value)}>{applications.data.map(a=><option key={a.id} value={a.id}>{a.user.name} — {a.job.title}</option>)}</select><input className="field" type="date" value={interview.data.date} onChange={e=>interview.setData('date',e.target.value)} required/><input className="field" type="time" value={interview.data.start_time} onChange={e=>interview.setData('start_time',e.target.value)} required/><input className="field" type="time" value={interview.data.end_time} onChange={e=>interview.setData('end_time',e.target.value)} required/><select className="field" value={interview.data.type} onChange={e=>interview.setData('type',e.target.value)}><option value="video">Video</option><option value="phone">Phone</option><option value="technical">Technical</option><option value="hr">HR</option><option value="final">Final</option><option value="on_site">On-site</option></select><button className="btn btn-primary">Schedule</button></div><input className="field mt-3" placeholder="Meeting URL for video interviews" value={interview.data.meeting_url} onChange={e=>interview.setData('meeting_url',e.target.value)}/>{Object.values(interview.errors).map((x,i)=><p className="error" key={i}>{x}</p>)}</form><div className="glass overflow-x-auto rounded-2xl"><table className="w-full min-w-[700px] text-left"><thead className="bg-white/5 text-sm text-slate-400"><tr><th className="p-4">Candidate</th><th className="p-4">Job</th><th className="p-4">Applied</th><th className="p-4">Status</th></tr></thead><tbody>{applications.data.map(a=><tr key={a.id} className="border-t border-[#1e3a5f]"><td className="p-4"><strong>{a.user.name}</strong><div className="text-sm text-slate-400">{a.user.email}</div></td><td className="p-4">{a.job.title}</td><td className="p-4 text-sm text-slate-400">{new Date(a.applied_at).toLocaleDateString()}</td><td className="p-4"><select className="field py-2" value={a.status} onChange={e=>update(a.id,e.target.value)}><option value="submitted">Submitted</option>{statuses.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></td></tr>)}</tbody></table>{!applications.data.length&&<div className="p-12 text-center text-slate-400">No candidates have applied yet.</div>}</div></DashboardLayout>
}
