import { Link, router, usePage } from '@inertiajs/react';
import { Menu, X } from 'lucide-react';
import { useState } from 'react';
import Brand from '../Components/Brand';

export default function PublicLayout({ children }) {
    const { auth, flash } = usePage().props; const [open, setOpen] = useState(false);
    return <div className="page-shell"><header className="sticky top-0 z-30 border-b border-blue-950/80 bg-[#07111f]/88 backdrop-blur-xl"><nav className="container-wide flex h-16 items-center justify-between"><Link href="/"><Brand/></Link><div className="hidden items-center gap-5 text-sm text-slate-300 md:flex"><Link href="/jobs" className="transition hover:text-white">Find jobs</Link>{auth.user ? <><Link href="/dashboard" className="transition hover:text-white">Dashboard</Link><button className="btn btn-secondary" onClick={() => router.post('/logout')}>Log out</button></> : <><Link href="/login" className="transition hover:text-white">Log in</Link><Link href="/register" className="btn btn-primary">Get started</Link></>}</div><button type="button" aria-label="Toggle navigation" aria-expanded={open} className="grid size-10 place-items-center rounded-lg border border-blue-900/70 text-slate-200 md:hidden" onClick={() => setOpen(!open)}>{open ? <X size={20}/> : <Menu size={20}/>}</button></nav>{open && <nav aria-label="Mobile navigation" className="container-wide grid gap-1 border-t border-blue-950 py-3 text-sm md:hidden"><Link href="/jobs" className="rounded-lg px-3 py-2.5 hover:bg-white/5" onClick={() => setOpen(false)}>Find jobs</Link>{auth.user ? <Link href="/dashboard" className="rounded-lg px-3 py-2.5 hover:bg-white/5">Dashboard</Link> : <><Link href="/login" className="rounded-lg px-3 py-2.5 hover:bg-white/5">Log in</Link><Link href="/register" className="rounded-lg px-3 py-2.5 hover:bg-white/5">Register</Link></>}</nav>}</header>{flash?.success && <div role="status" className="container-wide mt-4 rounded-xl border border-green-700/50 bg-green-900/30 p-3.5 text-sm text-green-200">{flash.success}</div>}{children}</div>;
}
